name: Deploy
on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Storybook on Github Pages
    steps:
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          path: build
